var passport = require('passport');

module.exports = {


  friendlyName: 'facebook oAuth API handler',


  description: 'oAuth',


  inputs: {

    // password: {
    //   description: 'The new, unencrypted password.',
    //   example: 'abc123v2',
    //   required: true
    // },
    //
    // token: {
    //   description: 'The password token that was generated by the `sendPasswordRecoveryEmail` endpoint.',
    //   example: 'gwa8gs8hgw9h2g9hg29hgwh9asdgh9q34$$$$$asdgasdggds',
    //   required: true
    // }

  },


  exits: {

    success: {
      description: 'Password successfully updated, and requesting user agent is now logged in.'
    },

    invalidToken: {
      description: 'The provided password token is invalid, expired, or has already been used.',
      responseType: 'expired'
    }

  },


  fn: async function (inputs, exits, env) {

    const { req, res, next } = env;

    passport.authenticate('facebook', { scope: ['email']})(req, res, next);

  }


};
